# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e38fb3e077d1f188b75e50d641fedb4f6b13c1c15fd0fd6ba15c7fa548a559619cd567e44bafcdba09661464efd13a0732fafa0a406821750d1fbf9a57d31d9

test:
  secret_key_base: 0553f52d74fc846ae871f7b0d4dc6f59ed6c113a7f74cec79d707b0f6cfe26767ea3bac01ab85e1283ed7deee2d26b93b01f660d1c6646b80eed15bdd0801966

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
